import React, { createContext, useState, useEffect, ReactNode } from 'react';

// Statically define translations as objects to avoid module resolution issues with JSON files.
const enTranslations = {
  "app_title": "AI Wallpaper Studio",
  "model_name": "Nano Banana",
  "app_subtitle": "Craft your perfect desktop background with AI",
  "footer_text": "Powered by Google Gemini. Designed by a World-Class React Engineer.",
  "tab_generate": "Generate Wallpaper",
  "tab_enhance": "Enhance Image",
  "prompt_label": "Describe the wallpaper you want to create",
  "prompt_placeholder": "e.g., An astronaut riding a majestic space whale through a nebula, digital art, vibrant colors",
  "prompt_tip": "Tip: Use Ctrl+Enter or Cmd+Enter to generate.",
  "negative_prompt_label": "What to avoid?",
  "negative_prompt_placeholder": "e.g., text, watermarks, blurry, hands",
  "optional": "Optional",
  "button_generate": "Generate",
  "button_generating": "Generating...",
  "button_enhance": "Enhance Quality",
  "button_enhancing": "Enhancing...",
  "button_download": "Download",
  "button_upscale": "Upscale",
  "button_upscaled": "Upscaled",
  "button_login": "Login",
  "button_signup": "Sign Up",
  "button_logout": "Logout",
  "button_login_signup": "Login or Sign Up",
  "welcome_user": "Welcome, {name}",
  "auth_login_title": "Login to your account",
  "auth_signup_title": "Create a new account",
  "auth_username_label": "Username",
  "auth_password_label": "Password",
  "auth_login_cta": "Login",
  "auth_signup_cta": "Create Account",
  "auth_switch_to_signup": "Don't have an account? Sign Up",
  "auth_switch_to_login": "Already have an account? Login",
  "aspect_ratio_label": "Aspect Ratio",
  "aspect_ratio_widescreen": "16:9 Widescreen",
  "aspect_ratio_portrait": "9:16 Portrait",
  "aspect_ratio_square": "1:1 Square",
  "style_preset_label": "Style Preset",
  "style_photorealistic": "Photorealistic",
  "style_digital_art": "Digital Art",
  "style_anime": "Anime",
  "style_synthwave": "Synthwave",
  "placeholder_title": "Your image will appear here",
  "placeholder_subtitle": "Describe your vision or upload an image to begin.",
  "loader_title": "Conjuring Pixels...",
  "loader_subtitle": "The AI is painting your vision. This might take a moment.",
  "upscaling_message": "Enhancing Details...",
  "error_title": "Oops, something went wrong.",
  "error_unexpected": "An unexpected error occurred.",
  "error_unexpected_upscale": "An unexpected error occurred during upscaling.",
  "error_unexpected_enhance": "An unexpected error occurred during enhancement.",
  "history_title": "History",
  "history_empty": "Your generated prompts will appear here.",
  "history_avoid_label": "Avoid",
  "history_auth_prompt_title": "Save Your Creations",
  "history_auth_prompt_subtitle": "Log in to see your past generations and save new ones.",
  "upload_label": "Upload an image to enhance",
  "upload_browse": "Browse files",
  "upload_drag_drop": "or drag and drop",
  "upload_formats": "PNG, JPG, GIF up to 10MB",
  "upload_ready": "Image ready for enhancement.",
  "upload_ready_subtitle": "Click the button to let the AI improve the quality.",
  "theme_change_label": "Change theme",
  "theme_light": "Light",
  "theme_dark": "Dark",
  "theme_amoled": "AMOLED Black",
  "theme_neon": "Neon Glow",
  "theme_glass": "Glassmorphism",
  "theme_aurora": "Blue Aurora",
  "theme_rose": "Rose Gold",
  "theme_cyberpunk": "Cyberpunk Purple",
  "theme_forest": "Forest Green",
  "theme_sand": "Desert Sand"
};

const arTranslations = {
  "app_title": "ستوديو خلفيات الذكاء الاصطناعي",
  "model_name": "نانو بنانا",
  "app_subtitle": "اصنع خلفية سطح المكتب المثالية باستخدام الذكاء الاصطناعي",
  "footer_text": "مدعوم من Google Gemini. تم التصميم بواسطة مهندس React من الطراز العالمي.",
  "tab_generate": "إنشاء خلفية",
  "tab_enhance": "تحسين صورة",
  "prompt_label": "صف الخلفية التي تريد إنشاءها",
  "prompt_placeholder": "مثال: رائد فضاء يركب حوتًا فضائيًا مهيبًا عبر سديم، فن رقمي، ألوان زاهية",
  "prompt_tip": "نصيحة: استخدم Ctrl+Enter أو Cmd+Enter للإنشاء.",
  "negative_prompt_label": "ما الذي يجب تجنبه؟",
  "negative_prompt_placeholder": "مثال: نصوص، علامات مائية، ضبابية، أيادي",
  "optional": "اختياري",
  "button_generate": "إنشاء",
  "button_generating": "جاري الإنشاء...",
  "button_enhance": "تحسين الجودة",
  "button_enhancing": "جاري التحسين...",
  "button_download": "تحميل",
  "button_upscale": "رفع الدقة",
  "button_upscaled": "تم رفع الدقة",
  "button_login": "تسجيل الدخول",
  "button_signup": "إنشاء حساب",
  "button_logout": "تسجيل الخروج",
  "button_login_signup": "تسجيل الدخول أو إنشاء حساب",
  "welcome_user": "أهلاً، {name}",
  "auth_login_title": "تسجيل الدخول إلى حسابك",
  "auth_signup_title": "إنشاء حساب جديد",
  "auth_username_label": "اسم المستخدم",
  "auth_password_label": "كلمة المرور",
  "auth_login_cta": "تسجيل الدخول",
  "auth_signup_cta": "إنشاء حساب",
  "auth_switch_to_signup": "ليس لديك حساب؟ إنشاء حساب",
  "auth_switch_to_login": "هل لديك حساب بالفعل؟ تسجيل الدخول",
  "aspect_ratio_label": "نسبة العرض إلى الارتفاع",
  "aspect_ratio_widescreen": "16:9 شاشة عريضة",
  "aspect_ratio_portrait": "9:16 طولي",
  "aspect_ratio_square": "1:1 مربع",
  "style_preset_label": "نمط مُعد مسبقًا",
  "style_photorealistic": "واقعي",
  "style_digital_art": "فن رقمي",
  "style_anime": "أنمي",
  "style_synthwave": "سينثويف",
  "placeholder_title": "ستظهر صورتك هنا",
  "placeholder_subtitle": "صف رؤيتك أو قم بتحميل صورة للبدء.",
  "loader_title": "استحضار البكسلات...",
  "loader_subtitle": "الذكاء الاصطناعي يرسم رؤيتك. قد يستغرق هذا بعض الوقت.",
  "upscaling_message": "تحسين التفاصيل...",
  "error_title": "عفوًا، حدث خطأ ما.",
  "error_unexpected": "حدث خطأ غير متوقع.",
  "error_unexpected_upscale": "حدث خطأ غير متوقع أثناء رفع الدقة.",
  "error_unexpected_enhance": "حدث خطأ غير متوقع أثناء التحسين.",
  "history_title": "السجل",
  "history_empty": "ستظهر طلباتك التي تم إنشاؤها هنا.",
  "history_avoid_label": "تجنب",
  "history_auth_prompt_title": "احفظ إبداعاتك",
  "history_auth_prompt_subtitle": "سجل الدخول لرؤية إبداعاتك السابقة وحفظ الجديدة.",
  "upload_label": "قم بتحميل صورة لتحسينها",
  "upload_browse": "تصفح الملفات",
  "upload_drag_drop": "أو قم بالسحب والإفلات",
  "upload_formats": "PNG, JPG, GIF حتى 10 ميجابايت",
  "upload_ready": "الصورة جاهزة للتحسين.",
  "upload_ready_subtitle": "انقر على الزر للسماح للذكاء الاصطناعي بتحسين الجودة.",
  "theme_change_label": "تغيير السمة",
  "theme_light": "فاتح",
  "theme_dark": "داكن",
  "theme_amoled": "أسود AMOLED",
  "theme_neon": "توهج نيون",
  "theme_glass": "زجاجي",
  "theme_aurora": "الشفق الأزرق",
  "theme_rose": "ذهبي وردي",
  "theme_cyberpunk": "سايبربانك بنفسجي",
  "theme_forest": "أخضر غابي",
  "theme_sand": "رمل الصحراء"
};

const kuTranslations = {
  "app_title": "ستۆدیۆی وێنەی دیواری AI",
  "model_name": "نانۆ مۆز",
  "app_subtitle": "وێنەی دیواری دیسکتۆپی تەواوی خۆت بە AI دروست بکە",
  "footer_text": "پشتگیری کراوە لەلایەن Google Gemini. دیزاین کراوە لەلایەن ئەندازیارێکی Reactی ئاست بەرز.",
  "tab_generate": "دروستکردنی وێنەی دیوار",
  "tab_enhance": "باشترکردنی وێنە",
  "prompt_label": "وەسفی ئەو وێنەی دیوارە بکە کە دەتەوێت دروستی بکەیت",
  "prompt_placeholder": "نموونە: ئاسمانەوانێک سواری نەهەنگێکی گەردوونی گەورە بووە بەناو تەمەئەستێرەیەکدا، هونەری دیجیتاڵی، ڕەنگی زیندوو",
  "prompt_tip": "ئامۆژگاری: Ctrl+Enter یان Cmd+Enter بەکاربێنە بۆ دروستکردن.",
  "negative_prompt_label": "لە چی دوور بکەویتەوە؟",
  "negative_prompt_placeholder": "نموونە: نووسین، ئاونیگار، لێڵی، دەست",
  "optional": "ئارەزوومەندانە",
  "button_generate": "دروستکردن",
  "button_generating": "دروست دەکرێت...",
  "button_enhance": "باشترکردنی کوالیتی",
  "button_enhancing": "باشتر دەکرێت...",
  "button_download": "داگرتن",
  "button_upscale": "گەورەکردنی وردبین",
  "button_upscaled": "وردبینی گەورەکرا",
  "button_login": "چوونەژوورەوە",
  "button_signup": "خۆتۆمارکردن",
  "button_logout": "چوونەدەرەوە",
  "button_login_signup": "چوونەژوورەوە یان خۆتۆمارکردن",
  "welcome_user": "بەخێربێیت، {name}",
  "auth_login_title": "بچۆ ژوورەوە بۆ هەژمارەکەت",
  "auth_signup_title": "هەژمارێکی نوێ دروست بکە",
  "auth_username_label": "ناوی بەکارهێنەر",
  "auth_password_label": "وشەی نهێنی",
  "auth_login_cta": "چوونەژوورەوە",
  "auth_signup_cta": "دروستکردنی هەژمار",
  "auth_switch_to_signup": "هەژمارێکت نییە؟ خۆتۆمار بکە",
  "auth_switch_to_login": "پێشتر هەژمارێکت هەیە؟ بچۆ ژوورەوە",
  "aspect_ratio_label": "ڕێژەی ڕەهەند",
  "aspect_ratio_widescreen": "١٦:٩ شاشەی پان",
  "aspect_ratio_portrait": "٩:١٦ ستوونی",
  "aspect_ratio_square": "١:١ چوارگۆشە",
  "style_preset_label": "شێوازی پێشوەختە",
  "style_photorealistic": "وێنەیی ڕاستی",
  "style_digital_art": "هونەری دیجیتاڵی",
  "style_anime": "ئەنیمی",
  "style_synthwave": "سینثوەیڤ",
  "placeholder_title": "وێنەکەت لێرە دەردەکەوێت",
  "placeholder_subtitle": "دیدگای خۆت وەسف بکە یان وێنەیەک باربکە بۆ دەستپێکردن.",
  "loader_title": "پیکسڵەکان ساز دەکرێن...",
  "loader_subtitle": "AI خەریکی کێشانی دیدگای تۆیە. ئەمە لەوانەیە کەمێک کات بخایەنێت.",
  "upscaling_message": "وردەکارییەکان باشتر دەکرێن...",
  "error_title": "ببورە، هەڵەیەک ڕوویدا.",
  "error_unexpected": "هەڵەیەکی چاوەڕواننەکراو ڕوویدا.",
  "error_unexpected_upscale": "هەڵەیەکی چاوەڕوانnەکراو لە کاتی گەورەکردنی وردبینیدا ڕوویدا.",
  "error_unexpected_enhance": "هەڵەیەکی چاوەڕوانnەکراو لە کاتی باشترکردندا ڕوویدا.",
  "history_title": "مێژوو",
  "history_empty": "داواکارییە دروستکراوەکانت لێرە دەردەکەون.",
  "history_avoid_label": "دوورکەوتنەوە",
  "history_auth_prompt_title": "داهێنانەکانت پاشەکەوت بکە",
  "history_auth_prompt_subtitle": "بچۆ ژوورەوە بۆ بینینی دروستکراوەکانی پێشووت و پاشەکەوتکردنی نوێیەکان.",
  "upload_label": "وێنەیەک باربکە بۆ باشترکردنی",
  "upload_browse": "گەڕانی فایلەکان",
  "upload_drag_drop": "یان ڕایکێشە و دایبنێ",
  "upload_formats": "PNG, JPG, GIF تا ١٠ مێگابایت",
  "upload_ready": "وێنەکە ئامادەیە بۆ باشترکردن.",
  "upload_ready_subtitle": "کرتە لە دوگمەکە بکە بۆ ئەوەی AI کوالیتییەکەی باشتر بکات.",
  "theme_change_label": "گۆڕینی থیم",
  "theme_light": "ڕووناک",
  "theme_dark": "تاریک",
  "theme_amoled": "ڕەشی AMOLED",
  "theme_neon": "درەوشاوەی نیۆن",
  "theme_glass": "شوشەیی",
  "theme_aurora": "شەفەقی شین",
  "theme_rose": "ئاڵتوونی گوڵی",
  "theme_cyberpunk": "سایبەرپەنکی مۆر",
  "theme_forest": "سەوزی دارستان",
  "theme_sand": "لمی بیابان"
};

type Language = 'en' | 'ar' | 'ku';

const translationsMap: Record<Language, Record<string, string>> = {
  en: enTranslations,
  ar: arTranslations,
  ku: kuTranslations,
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translations: Record<string, string>;
}

export const LanguageContext = createContext<LanguageContextType>({
  language: 'ku',
  setLanguage: () => {},
  translations: {},
});

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ku');
  const [translations, setTranslations] = useState<Record<string, string>>(translationsMap.ku);

  useEffect(() => {
    const detectedLang = navigator.language.split('-')[0];
    if (detectedLang === 'ar' || detectedLang === 'ku') {
      setLanguage(detectedLang);
    }
  }, []);

  useEffect(() => {
    setTranslations(translationsMap[language] || translationsMap.ku);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};
